### ISSUE TITLE
Hello! Site appears down?

### ISSUE THREAD

**Issue by viking2917** [sveinbjornt/sagadb.org#1]
Hello! Not sure if you are the owner of the sagadb.org website itself, but it seems to have been down the last few days. 

Love the site! Hope you can bring it back!

**Comment by rosielocks** [comment]
I hope the issue is fixed soon - I am using the database for my Master's thesis!

**Comment by viking2917** [comment]
@rosielocks you probably know already, but you can find a lot of the content at the Internet Archive if needed: https://web.archive.org/web/2021*/sagadb.org

**Comment by rosielocks** [comment]
@viking2917 I actually completely forgot that was an option. Thank you so much - I downloaded all the PDFs from the site. Shame I didn't think to do that before!

**Comment by viking2917** [comment]
post your thesis here when you're done  :)

**Comment by sveinbjornt** [comment]
My server is currently down, am working on fixing the issue. Hopefully everything will be back online in a day or two.

**Comment by viking2917** [comment]
@sveinbjornt woohoo! Thanks so much!!

**Comment by sveinbjornt** [comment]
The sagadb.org website is finally back online.

**Comment by viking2917** [comment]
@sveinbjornt thank you!!! such an awesome resource!
